# Generated by Django 3.1.2 on 2020-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('txt', models.FileField(upload_to='chat_files/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
