# Generated by Django 3.1.2 on 2020-10-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupChat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
    ]
